version: '3'

#Docker Networks
networks:
  apihost:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-api-host
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      apihost:
    ports:
    - 8082:80
  #MySQL Service
  mysql:
    image: mysql:5.7.29
    container_name: mysql-api-host
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "33063:3306"
    environment:
      MYSQL_DATABASE: meteoapi
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - apihost
  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user_id: 1000
    working_dir: /var/www
    image: php
    container_name: php-api-host
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - apihost
